const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  SIGNER_ADDED: 'SIGNER_ADDED',
  SIGNING_REQUEST_SENT: 'SIGNING_REQUEST_SENT',
  EMAIL_QUEUED: 'EMAIL_QUEUED',
  EMAIL_DELIVERED: 'EMAIL_DELIVERED',
  EMAIL_FAILED: 'EMAIL_FAILED',
  FIELD_COMPLETED: 'FIELD_COMPLETED',
  SIGNATURE_SUBMITTED: 'SIGNATURE_SUBMITTED',
  DOCUMENT_FINALIZED: 'DOCUMENT_FINALIZED',
  SIGNATURE_ADDED: 'SIGNATURE_ADDED',
  DOCUMENT_SIGNED: 'DOCUMENT_SIGNED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
});

module.exports = { AUDIT_ACTIONS };
